version: '3'
services:
  db: 
    container_name: postgresdb
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '5432:5432'
  server:
    container_name: node-challenge-server
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - '9001:9001'
